batch_size: 128
epochs: 80
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /content/data
pretrained_model: "/content/drive/MyDrive/03_Colab Notebooks/DLBasics2023_colab/GraduationProject/model/pretrained_clip.pth"

# Evaluation
model_path: 