batch_size: 128 
epochs: 80
lr: 0.001
weight_decay: 0.0001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /workspaces/PythonProjects/dl_lecture_competition_pub/data
pretrained_model: "/workspaces/PythonProjects/dl_lecture_competition_pub/model/pretrained_encoder.pth"

# Evaluation
model_path: 
